import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Header } from "@/widgets/header";

export const metadata: Metadata = {
  title: "Проекты",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }: PropsWithChildren<unknown>) {
  return (
    <div className="flex h-full flex-col">
      {/* <Header /> */}
      {children}
    </div>
  );
}
