import type { Metadata } from "next";
import { Mulish, Source_Code_Pro, Geist } from "next/font/google";
import "./styles";
import { cn } from "@/shared/utils/utils";
import Provider from "@/shared/api/Provider";
import TimerProvider from "@/widgets/timeTracker/providers/TimerProvider";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/widgets/themeProvider";
import { setInitialColorMode } from "@/shared/utils/setInitialColorMode";
import Script from "next/script";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modalCreateCollection,
  modalEditCollection,
  modalSetting,
}: Readonly<{
  children: React.ReactNode;
  modalCreateCollection: React.ReactNode;
  modalEditCollection: React.ReactNode;
  modalSetting: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning className={cn("font-sans", geist.variable)}>
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {setInitialColorMode}
        </Script>
      </head>
      <body
        className={cn(
          mulish.variable,
          sourceCodePro.variable,
          "antialiased",
          "flex flex-col p-3"
        )}
      >
        <div className="absolute top-1/2 left-1/2 -translate-1/2 h-screen w-screen overflow-hidden -z-1">
          <div className="blop1"></div>
          <div className="blop2"></div>
          <div className="blop3"></div>
        </div>

        <Provider>
          <ThemeProvider />
          <TimerProvider>{children}</TimerProvider>
          <Toaster />
          {modalCreateCollection}
          {modalEditCollection}
          {modalSetting}
        </Provider>
      </body>
    </html>
  );
}
