import { PropsWithChildren } from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Главная",
  description: "Generated by create next app",
};

export default function SiteLayout({ children }: PropsWithChildren<unknown>) {
  return <div className="flex h-full flex-col">{children}</div>;
}
